import './globals.css';
import {Mouse_Memoirs} from 'next/font/google';

const Mouse = Mouse_Memoirs({
	subsets: ['latin'],
	weight: ['400'],
	display: 'swap',
});

export const metadata = {
	title: 'Superklok Labs',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
		<body className={Mouse.className}>{children}</body>
		</html>
	);
}
