export const LandingData = [
	{
		src: 'Landing/Track1.jpg',
		bg: '#008567',
		link: 'https://youtu.be/zl8n6uWK3uo',
		delay: 0.1,
	},
	{
		src: 'Landing/Track2.jpg',
		bg: '#5B0097',
		link: 'https://youtu.be/6cG6HLHDzhI',
		delay: 0.3,
	},
	{
		src: 'Landing/Track3.jpg',
		bg: '#228B22',
		link: 'https://youtu.be/7yRK4rkA9Zs',
		delay: 0.2,
	},
	{
		src: 'Landing/Track4.jpg',
		bg: '#1A1A6B',
		link: 'https://youtu.be/pY_Mv0IKoN4',
		delay: 0.2,
	},
	{
		src: 'Landing/Track5.jpg',
		bg: '#B13319',
		link: 'https://youtu.be/_ddWZoMhlO0',
		delay: 0.3,
	},
	{
		src: 'Landing/Track6.jpg',
		bg: '#3F00BF',
		link: 'https://youtu.be/fHx-4ip4iqU',
		delay: 0.25,
	},
];

export const Services = [
	{
		icon: '/Services/Frame-0.png',
		title: 'React',
		link: 'https://react.dev/learn',
	},
	{
		icon: '/Services/Frame-1.png',
		title: 'Next.js',
		link: 'https://nextjs.org/docs',
	},
	{
		icon: '/Services/Frame-2.png',
		title: 'JavaScript ES6',
		link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
	},
	{
		icon: '/Services/Frame-3.png',
		title: 'After Effects',
		link: 'https://helpx.adobe.com/ca/after-effects/user-guide.html',
	},
	{
		icon: '/Services/Frame-4.png',
		title: 'FL Studio',
		link: 'https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/',
	},
	{
		icon: '/Services/Frame-5.png',
		title: 'DxO PhotoLab',
		link: 'https://userguides.dxo.com/photolab/en/overview/',
	},
];

export const ConnectFeatures = [
	{
		icon: '/Connect/Frame-2.png',
		title: 'LinkedIn',
		link: 'https://www.linkedin.com/company/superkloklabs',
		desc: 'Follow us on LinkedIn for company updates & exclusive content!',
	},
	{
		icon: '/Connect/Frame-0.png',
		title: 'GitHub',
		link: 'https://github.com/Superklok',
		desc: 'All Superklok Labs repositories are publicly available on our GitHub!',
	},
	{
		icon: '/Connect/Frame-1.png',
		title: 'YouTube',
		link: 'https://www.youtube.com/channel/UCNnuDVs9xXqT5PrbL-uP7Vw',
		desc: 'Check out music videos & virtual reality on our YouTube channel!',
	},
];

export const DevOpsFeatures = [
	{
		icon: '/DevOps/Frame-0.png',
		title: 'Docker',
		link: 'https://docs.docker.com/',
		desc: 'Enhancing legacy apps by turning them into images then capturing running instances of them called containers using Docker. This increases scalability and facilitates cross-platform compatibility.',
	},
	{
		icon: '/DevOps/Frame-1.png',
		title: 'Kubernetes',
		link: 'https://kubernetes.io/docs/home/',
		desc: 'A great way to manage your containers is by orchestrating them in pods using Kubernetes. This allows you to store secrets, obtain SSL certificates, and quickly scale up an app across many nodes.',
	},
	{
		icon: '/DevOps/Frame-2.png',
		title: 'Amazon Web Services',
		link: 'https://aws.amazon.com/',
		desc: 'Deploying the full AWS DevOps arsenal of tools to tackle all your DevOps Engineering needs.',
	},
];

export const AboutUs = [
	{
		title: 'The Company',
		desc: 'Superklok Labs is an IT consulting firm that specializes in JavaScript, React, Next.js, AWS DevOps Engineering, PC building, French/English Translation, ',
		music: 'Music Production',
		desc4: ' & Graphic Design.',
	},
	{
		title: 'Our Mission',
		desc: 'Conceptualizing then creating JavaScript Applications, Custom PCs, ',
		music: 'Music',
		desc4: ', Graphics, and Videos that stand out thanks to unique design choices.',
	},
	{
		title: 'Fully Bilingual',
		desc: 'We\'re a Canadian business so all our consultations are offered in both English and French.',
	},
	{
		title: 'Questions?',
		desc: 'Please reach out to ',
		desc2: ' with any general enquiries and contact ',
		desc3: ' to book a consultation.',
		info: 'info@superklok.com',
		sales: 'sales@superklok.com',
	},
];

export const ContainerData = [
	{
		icon: '/Containers/Frame-15.png',
		title: '[EN] This Website',
		desc: 'The LIVE running production version of the Superklok Labs corporate website, coded in Next.js and React.',
		docker: 'https://hub.docker.com/r/superklok/superkloklabs',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/SuperklokLabs',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-0.jpg',
		title: '[EN] Swingcars',
		desc: 'Swingcars is a social media app intended to facilitate vehicle swapping between drivers.',
		docker: 'https://hub.docker.com/r/superklok/swingcarsdotnet',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/SwingcarsDotNet',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-2.jpg',
		title: '[EN] Jet Wheel Reel',
		desc: 'Jet Wheel Reel is an educational site that demonstrates a wheel change on a Beechcraft 1900D.',
		docker: 'https://hub.docker.com/r/superklok/jetwheelreeldotcom',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/JetWheelReelDotCom',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-1.jpg',
		title: '[EN] Current Courant',
		desc: 'The Current Courant is newspaper app that allows users to publish their own articles.',
		docker: 'https://hub.docker.com/r/superklok/currentcourantdotcom',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/CurrentCourantDotCom',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-3.png',
		title: '[EN] Slider Piler',
		desc: 'Slider Piler is an online ordering app which currently consists of a create-your-own sandwich builder.',
		docker: 'https://hub.docker.com/r/superklok/sliderpilerdotcom',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/SliderPilerDotCom',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-4.jpg',
		title: '[EN] TrevMorin.com',
		desc: 'TrevMorin.com is a portfolio website that showcases each web design concept created by Superklok Labs.',
		docker: 'https://hub.docker.com/r/superklok/trevmorindotcom',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/TrevMorinDotCom',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-5.jpg',
		title: '[EN] Superklok Labs',
		desc: 'The Superklok Labs company website provides a technical and detailed description of each available service.',
		docker: 'https://hub.docker.com/r/superklok/superklokdotcom',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/SuperklokDotCom',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-6.jpg',
		title: '[EN] React Crypto Stats',
		desc: 'Crypto Stats is a cryptocurrency analysis app that uses Chart.js to illustrate market performance.',
		docker: 'https://hub.docker.com/r/superklok/reactcryptostats',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/ReactCryptoStats',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-7.jpg',
		title: '[EN] React Candy Crush',
		desc: 'This is a React replica of Candy Crush for PC that was coded with the useState and useEffect React Hooks.',
		docker: 'https://hub.docker.com/r/superklok/reactcandycrush',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/ReactCandyCrush',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-8.png',
		title: '[EN] React Task Tracker',
		desc: 'A to-do list that demonstrates CRUD functionality. V1.19.1 uses a database and the demo, v2.2.1, uses the DOM.',
		docker: 'https://hub.docker.com/r/superklok/reacttasktracker',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/ReactTaskTracker',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-9.jpg',
		title: '[FR] Swingcars',
		desc: 'Swingcars est une appli de médias sociaux destinée à faciliter l\'échange de véhicules entre conducteurs.',
		docker: 'https://hub.docker.com/r/superklok/swingcarspointca',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/SwingcarsPointCa',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-11.jpg',
		title: '[FR] Jet Wheel Reel',
		desc: 'Jet Wheel Reel est un site éducatif qui vous montrez comment changer le roue d\'un Beechcraft 1900D.',
		docker: 'https://hub.docker.com/r/superklok/jetwheelreelpointca',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/JetWheelReelPointCa',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-10.jpg',
		title: '[FR] Current Courant',
		desc: 'Le Current Courant est une appli journalistique qui vous permet de publier vos propres articles.',
		docker: 'https://hub.docker.com/r/superklok/currentcourantpointca',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/CurrentCourantPointCa',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-12.png',
		title: '[FR] Slider Piler',
		desc: 'Slider Piler est une application de resto qui consiste actuellement d\'un outil de création de sandwichs.',
		docker: 'https://hub.docker.com/r/superklok/sliderpilerpointca',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/SliderPilerPointCa',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-13.jpg',
		title: '[FR] TrevMorin.ca',
		desc: 'TrevMorin.ca est un site web de portfolio qui présente chaque concept d\'appli créé par Superklok Labs.',
		docker: 'https://hub.docker.com/r/superklok/trevmorinpointca',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/TrevMorinPointCa',
		githubImg: '/Connect/Frame-0.png',
	},
	{
		icon: '/Containers/Frame-14.jpg',
		title: '[FR] Superklok Labs',
		desc: 'Le site web de l\'entreprise Superklok Labs fournit une description détaillée de chaque service disponible.',
		docker: 'https://hub.docker.com/r/superklok/superklokpointca',
		dockerImg: '/DevOps/Frame-0.png',
		github: 'https://github.com/Superklok/SuperklokPointCa',
		githubImg: '/Connect/Frame-0.png',
	},
];
